### ISSUE TITLE
How to setup runner for more than 1 organization in GHE?

### ISSUE THREAD

**Issue by mssanjay** [redhat-actions/openshift-actions-runner-chart#14]
Hi,
I have my repos in multiple ORGS in our GHE. How can I configure single runner for multiple ORGS? 
I see the below value to be set. This does not accept multiple values.

githubOwner: "ORG1"

**Comment by tetchel** [comment]
I do not think this is possible given the APIs GitHub provides. You have to create different runners for each different org.

The [registration token endpoint](https://docs.github.com/en/rest/reference/actions#create-a-registration-token-for-an-organization) only accepts one organization, and the `config.sh` script only accepts one `registration_url`.

It does not look like there is an issue for multi-org runners, but there is [this one for multi-repo runners](https://github.com/actions/runner/issues/245), which is closed with org runners as the solution. Similarly, there is no way to have a runner bound to multiple repos that are in different orgs or no org.

**Comment by tetchel** [comment]
OK, it looks like there is GHE support for this I was not aware of.

https://docs.github.com/en/actions/hosting-your-own-runners/managing-access-to-self-hosted-runners-using-groups#creating-a-self-hosted-runner-group-for-an-enterprise

You can create a runner group which has access to multiple organizations. Then, create an *enterprise-scoped runner*, and add it to that group.

I do not have access to a GHE instance to test this. But I expect this may be a use-case for allowing the `githubOrg` value  to be empty if `GITHUB_DOMAIN` is set to something other than `github.com`. Then we can create runners at the enterprise scope. I think that is the only change that is necessary.

**Comment by tetchel** [comment]
https://github.com/redhat-actions/openshift-actions-runner-chart/blob/main/templates/deployment.yaml#L54

https://github.com/redhat-actions/openshift-actions-runners/blob/main/base/register.sh#L9

**Comment by mssanjay** [comment]
Thank you very much! I will have to reach out to our Enterprise owners to set this up at Enterprise scope. This is very helpful.
