### ISSUE TITLE
Integrate helm-certifier

### ISSUE THREAD

**Issue by tetchel** [redhat-actions/openshift-actions-runner-chart#7]
We will add the helm-certifier to this project. But, I consider these ~two~ three issues blockers before we can reasonably do that.

https://github.com/redhat-certification/chart-verifier/issues/26
https://github.com/redhat-certification/chart-verifier/issues/32
https://github.com/redhat-certification/chart-verifier/issues/33

**Comment by sbose78** [comment]
Plus everything on https://github.com/redhat-certification/chart-verifier/issues/created_by/tetchel

**Comment by rtaniwa** [comment]
Should this be marked complete for 209, or should we move to 210?

**Comment by tetchel** [comment]
Let us keep it until there is a release

**Comment by divyansh42** [comment]
Issue to track the release :point_right: https://github.com/redhat-actions/chart-verifier/issues/1
